name = "yk"
uuid = "6e154f78-3de9-41b6-9092-2af2da77e4bd"
authors = ["YuttariKanata <yuttarikanata@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
